# config server
config: 
  uri: "http://localhost:8888"

# eureka client 
eureka:
  client:
    uri: "http://localhost:8761/eureka"

# test
message: "Voici mon message"

# project database connection
project: 
  datasource:
    url: jdbc:postgresql://localhost:5432/invest_gate_projects
    username: postgres
    password: postgresql

# admin database connection
admin: 
  datasource:
    url: jdbc:postgresql://localhost:5432/invest_gate_admins
    username: postgres
    password: postgresql

# investor database connection
investor: 
  datasource:
    url: jdbc:postgresql://localhost:5432/invest_gate_investors
    username: postgres
    password: postgresql

# student database connection
student: 
  datasource:
    url: jdbc:postgresql://localhost:5432/invest_gate_students
    username: postgres
    password: postgresql

agreement: 
  datasource:
    url: jdbc:postgresql://localhost:5432/invest_gate_agreements
    username: postgres
    password: postgresql

# config email 
mail:
  username: yasaiteams002@gmail.com
  password: tjtdrvdfzqxghmkv

#test: 
#  datasource:
#    url: jdbc:postgresql://localhost:5432/invest_gate_admins
#    username: postgres
#    password: postgresql


# jdbc:mysql://localhost:3306

   


